



namespace XXY.Cargo.DataContext{
	public enum Sequences{
	
		AGENCYCHARGE_OVERSEAAGENCY_SEQ  ,
			
		AGENCY_CITYS_COUNT_SEQ  ,
			
		AGENCY_COUNT_SEQ  ,
			
		AIR_IMPORT_SEQ  ,
			
		AIR_ORDER_NO_SEQ  ,
			
		AIR_ORDER_SEQ  ,
			
		BASE_AIRSHIPPING_SUB_SEQ  ,
			
		BASE_ALLIANCE_COMPANY_SEQ  ,
			
		BASE_ALLIANCE_SEQ  ,
			
		BASE_BLACKLIST_SEQ  ,
			
		BASE_CAMPAIGN_REWARD_SEQ  ,
			
		BASE_COMMISSION_DISCOUNT_SEQ  ,
			
		BASE_COMPANY_AUTHORITY_SEQ  ,
			
		BASE_COMPANY_FINANCIAL_SEQ  ,
			
		BASE_COMPANY_FINANCING_SEQ  ,
			
		BASE_COMPANY_STRIPE_SEQ  ,
			
		BASE_COMPANY_THUNES_KYB_SEQ  ,
			
		BASE_COMPANY_WHITELIST_SEQ  ,
			
		BASE_EXCHANGE_RATE_SEQ  ,
			
		BASE_EXPRESS_SUB_SEQ  ,
			
		BASE_FEE_STANDARD_SEQ  ,
			
		BASE_HOMEPAGE_PICTURE_SEQ  ,
			
		BASE_JOB_LOG_SEQ  ,
			
		BASE_LIST_INFO_SEQ  ,
			
		BASE_MEMOS_SEQ  ,
			
		BASE_MOBILE_VERIFYCODE_SEQ  ,
			
		BASE_NEWS_REPLY_SEQ  ,
			
		BASE_OTHER_ADVERTISEMENT_SEQ  ,
			
		BASE_PAY_SUPPLIER_SEQ  ,
			
		BASE_PERMISSION_GROUP_SEQ  ,
			
		BASE_PLATFORM_REWARD_SEQ  ,
			
		BASE_ROLE_PERMISSION_GROUP_SEQ  ,
			
		BASE_ROLE_PERMISSION_SEQ  ,
			
		BASE_ROLE_SEQ  ,
			
		BASE_SEASHIPPING_SUB_SEQ  ,
			
		BASE_SERVICE_CHARGE_SEQ  ,
			
		BASE_SPREAD_BOX_SEQ  ,
			
		BASE_SPREAD_SEQ  ,
			
		BASE_WAREHOUSE_REALTED_SEQ  ,
			
		BASE_WAREHOUSE_SEQ  ,
			
		BILL_EXCHANGE_RATE_SEQUENCE  ,
			
		BILL_TEMPLATE_DETAIL_SEQ  ,
			
		BILL_TEMPLATE_SEQ  ,
			
		BOOKINGORDER_FREEDETENTION_SEQ  ,
			
		BOOKING_AGENCY_CHARGE_SEQ  ,
			
		BOOKING_ORDER_APPROVER_SEQ  ,
			
		BOOKING_ORDER_BL_CONTAINER_SEQ  ,
			
		BOOKING_ORDER_BL_SEQ  ,
			
		BOOKING_ORDER_CONTAINER_SEQ  ,
			
		BOOKING_ORDER_FILE_SEQ  ,
			
		BOOKING_ORDER_OTHER_SEQ  ,
			
		BOOKING_ORDER_PRESALE_SEQ  ,
			
		BOOKING_ORDER_RATE_SEQ  ,
			
		BOOKING_ORDER_SEQ  ,
			
		BOOKING_ORDER_SI_SEQ  ,
			
		BOOKING_ORDER_SO_SEQ  ,
			
		BOOKING_ORDER_SURCHARGE_SEQ  ,
			
		CALISTA_BOOKING_CARGO_SEQ  ,
			
		CALISTA_BOOKING_CONTAINER_SEQ  ,
			
		CALISTA_FREIGHT_BOOKING_SEQ  ,
			
		CARGOTRACK_E_BK_SEQ  ,
			
		CARRIERDATA_LACK_SEQ  ,
			
		CARRIER_ONLINE_SEQ  ,
			
		CHOICE_SUPPLIER_SEQ  ,
			
		COMPANY_AUTHENTICATION_SEQ  ,
			
		COMPANY_CHECK_SEQ  ,
			
		COMPANY_CREDITREPORT_SEQ  ,
			
		COMPANY_SEQ  ,
			
		COMPANY_SOURCE_SEQ  ,
			
		COMPANY_THUNES_KYB_BANK_SEQ  ,
			
		COMPANY_THUNES_KYB_EXTEND_SEQ  ,
			
		COMPANY_THUNES_RECEIVE_SEQ  ,
			
		CONTRACTS_DETAIL_SEQ  ,
			
		CONTRACTS_SEQ  ,
			
		CONTRACT_ITEML_SEQ  ,
			
		CONTRACT_SURCHARGE_SEQ  ,
			
		CONTRACT_TEMPLATE_SEQ  ,
			
		CUSTOMER_ACCOUNT_DETAIL_SEQ  ,
			
		CUSTOMER_AGENCY_CHARGE_SEQ  ,
			
		CUSTOMER_INTEGRAL_DETAIL_SEQ  ,
			
		CUSTOMER_PRODUCT_TEU_SEQ  ,
			
		CUSTOMER_RATE_PUSH_SEQ  ,
			
		CUSTOMER_RATE_RULE_SEQ  ,
			
		CUSTOMER_SCN_SEQ  ,
			
		CUS_DECLAR_SUB_SEQ  ,
			
		DELETE_PRODUCT_SURCHARGE_SEQ  ,
			
		DEMAND_AIR_SEQ  ,
			
		DEMAND_FBA_SEQ  ,
			
		DEMAND_LCL_SEQ  ,
			
		DICT_SEQ  ,
			
		ECL_AGENCYFEE_PRODUCT_SEQ  ,
			
		ECL_ORDER_NO_SEQ  ,
			
		ECL_PACK_CONTAINER_SEQ  ,
			
		FCLMAIN_GROUPRATEDETAIL_SEQ  ,
			
		FCLMAIN_GROUPRATE_SCHEDULE_SEQ  ,
			
		FCL_CARRIER_SUBSCRIBE_SEQ  ,
			
		FEEDBACK_SEQ  ,
			
		FF_ADVANTAGE_SEQ  ,
			
		FF_ADVERTISEMENTS_SEQ  ,
			
		FF_ADVERTISEMENT_AGENCY_SEQ  ,
			
		FF_ADVERTISEMENT_AIR_SEQ  ,
			
		FF_ADVERTISEMENT_FBA_SEQ  ,
			
		FF_ADVERTISEMENT_LCL_SEQ  ,
			
		FF_ADVERTISEMENT_LOCATION_SEQ  ,
			
		FF_AGENCY_CHARGE_COMPANY_SEQ  ,
			
		FF_AGENCY_CHARGE_SEQ  ,
			
		FF_AIRBRANCH_PRODUCT_LIST_SEQ  ,
			
		FF_AIRBRANCH_PRODUCT_SEQ  ,
			
		FF_AIRBRANCH_RATE_LIST_SEQ  ,
			
		FF_AIRMAIN_PREEVIP_RULE_SEQ  ,
			
		FF_AIRMAIN_PRODUCT_LIST_SEQ  ,
			
		FF_AIRMAIN_PRODUCT_RULE_SEQ  ,
			
		FF_AIRMAIN_PRODUCT_SEQ  ,
			
		FF_AIRMAIN_PRODUCT_VIA_SEQ  ,
			
		FF_AIRMAIN_RATE_DETAIL_SEQ  ,
			
		FF_AIRMAIN_RATE_LIST_SEQ  ,
			
		FF_AIRMAIN_RATE_SEQ  ,
			
		FF_AIR_CUSTOMER_RULE_SEQ  ,
			
		FF_AIR_INQUIRY_PRODUCT_SEQ  ,
			
		FF_AIR_INQUIRY_SEQ  ,
			
		FF_AIR_ORDER_BL_SEQ  ,
			
		FF_AIR_ORDER_BOOKING_SEQ  ,
			
		FF_AIR_ORDER_CHARGE_SEQ  ,
			
		FF_AIR_ORDER_DESTFEE_SEQ  ,
			
		FF_AIR_ORDER_SI_SEQ  ,
			
		FF_AIR_PRODUCT_SEQ  ,
			
		FF_AIR_PRODUCT_SUPPLIER_SEQ  ,
			
		FF_AIR_RATE_CUSTOMER_SEQ  ,
			
		FF_AIR_RATE_DETAIL_SEQ  ,
			
		FF_AIR_RATE_SEQ  ,
			
		FF_AIR_SEARCHRATE_LOG_SEQ  ,
			
		FF_AIR_SURCHARGE_AIRPORT_SEQ  ,
			
		FF_AIR_SURCHARGE_CUSTOMER_SEQ  ,
			
		FF_AIR_SURCHARGE_PRODUCT_SEQ  ,
			
		FF_AIR_SURCHARGE_SEQ  ,
			
		FF_AREA_SURCHARGES_SEQ  ,
			
		FF_ASYNC_PEERVIP_SEQ  ,
			
		FF_ASYNC_RATE_SEQ  ,
			
		FF_BANK_ACCOUNT_SEQ  ,
			
		FF_BILL_CONTAINER_SEQ  ,
			
		FF_BILL_LIST_INVOICE_SEQ  ,
			
		FF_BILL_LIST_SEQ  ,
			
		FF_BILL_SAP_SEQ  ,
			
		FF_BILL_SEQ  ,
			
		FF_BLACKLIST_SEQ  ,
			
		FF_BUY_SERVICE_SEQ  ,
			
		FF_CARRIER_CONTRAST_SEQ  ,
			
		FF_CRM_SEQ  ,
			
		FF_CUSTOMER_MONTHLY_SEQ  ,
			
		FF_CUSTOMER_SALES_SEQ  ,
			
		FF_CUSTOMER_SEQ  ,
			
		FF_CUSTOMER_USER_SEQ  ,
			
		FF_CUSTOMER_VISIT_SEQ  ,
			
		FF_DANGEROU_SURCHARGE_SEQ  ,
			
		FF_DELETE_AREA_SURCHARGE_SEQ  ,
			
		FF_ECLPRODUCTSUPPLIER_RULE_SEQ  ,
			
		FF_ECL_AGENCYFEE_CUSTOMER_SEQ  ,
			
		FF_ECL_AGENCYFEE_SEQ  ,
			
		FF_ECL_CUSTOMER_RULE_SEQ  ,
			
		FF_ECL_IMPORT_DECLARE_SEQ  ,
			
		FF_ECL_IMPORT_SEQ  ,
			
		FF_ECL_INQUIRY_PRODUCT_SEQ  ,
			
		FF_ECL_INQUIRY_SEQ  ,
			
		FF_ECL_ORDER_BOOKING_SEQ  ,
			
		FF_ECL_ORDER_CHARGE_SEQ  ,
			
		FF_ECL_ORDER_DECLARE_SEQ  ,
			
		FF_ECL_ORDER_SEQ  ,
			
		FF_ECL_PRODUCT_FBA_SEQ  ,
			
		FF_ECL_PRODUCT_LEVEL_SEQ  ,
			
		FF_ECL_PRODUCT_LIST_SEQ  ,
			
		FF_ECL_PRODUCT_SEQ  ,
			
		FF_ECL_PRODUCT_SUPPLIER_SEQ  ,
			
		FF_ECL_PRODUCT_VIPRULE_SEQ  ,
			
		FF_ECL_RATE_CUSTOMER_SEQ  ,
			
		FF_ECL_RATE_DETAIL_SEQ  ,
			
		FF_ECL_RATE_LIST_SEQ  ,
			
		FF_ECL_RATE_SEQ  ,
			
		FF_ECL_SEARCHRATE_LOG_SEQ  ,
			
		FF_ECL_TOKEN_CUSTOMER_SEQ  ,
			
		FF_ECL_TOKEN_SEQ  ,
			
		FF_ECL_ZONE_COUNTRY_SEQ  ,
			
		FF_ECL_ZONE_FBA_SEQ  ,
			
		FF_ECL_ZONE_SEQ  ,
			
		FF_EXCHANGE_RATE_SEQ  ,
			
		FF_FCLBRANCH_CPL_SEQ  ,
			
		FF_FCLBRANCH_CP_RATE_SEQ  ,
			
		FF_FCLBRANCH_CP_SEQ  ,
			
		FF_FCLBRANCH_CRS_SEQ  ,
			
		FF_FCLMAIN_CPL_SEQ  ,
			
		FF_FCLMAIN_CPRATE_DETAIL_SEQ  ,
			
		FF_FCLMAIN_CP_PEERVIP_SEQ  ,
			
		FF_FCLMAIN_CP_RATE_SEQ  ,
			
		FF_FCLMAIN_CP_SEQ  ,
			
		FF_FCLMAIN_CP_VIA_SEQ  ,
			
		FF_FCLMAIN_CRS_SEQ  ,
			
		FF_FCLMAIN_GROUPRATE_LIST_SEQ  ,
			
		FF_FCLMAIN_GROUP_PEERVIP_SEQ  ,
			
		FF_FCLMAIN_GROUP_RATE_SEQ  ,
			
		FF_FCLMAIN_PEERVIP_RULE_SEQ  ,
			
		FF_FCLMAIN_PRODUCT_GROUP_SEQ  ,
			
		FF_FCLMAIN_PRODUC_SEQ  ,
			
		FF_FCLMAIN_RATE_DETAIL_SEQ  ,
			
		FF_FCLMAIN_RATE_SEQ  ,
			
		FF_FCLRATE_MODE_SEQ  ,
			
		FF_FCLSURCHARGE_DGLEVEL_SEQ  ,
			
		FF_FCLSURCHARGE_DGP_SEQ  ,
			
		FF_FCLSURCHARGE_DG_SEQ  ,
			
		FF_FCLSURCHARGE_OWLEVEL_SEQ  ,
			
		FF_FCLSURCHARGE_OWP_SEQ  ,
			
		FF_FCLSURCHARGE_OW_SEQ  ,
			
		FF_FCLSURCHARGE_PRODUCT_SEQ  ,
			
		FF_FCLSURCHARGE_RFP_SEQ  ,
			
		FF_FCLSURCHARGE_RF_SEQ  ,
			
		FF_FCLSURCHARGE_SEQ  ,
			
		FF_FCL_BRANCH_RATE_SEQ  ,
			
		FF_FCL_LAND_RATE_SEQ  ,
			
		FF_FCL_SPACE_SEQ  ,
			
		FF_FCL_SPACE_SO_SEQ  ,
			
		FF_FF_AIRBRANCH_RATE_SEQ  ,
			
		FF_FINANCE_CHECK_BILL_SEQ  ,
			
		FF_FINANCE_CHECK_EXPENSES_SEQ  ,
			
		FF_FINANCE_CHECK_SEQ  ,
			
		FF_FTFCL_ORDER_CHARGE_SEQ  ,
			
		FF_FTLCL_ORDER_CHARGE_SEQ  ,
			
		FF_HOMEPAGE_CONFIGURE_SEQ  ,
			
		FF_HOMEPAGE_CONTACTS_SEQ  ,
			
		FF_HOMEPAGE_COREBUSINESS_SEQ  ,
			
		FF_HOMEPAGE_MENU_SEQ  ,
			
		FF_HOMEPAGE_SEQ  ,
			
		FF_INQUIRY_PRODUCT_SEQ  ,
			
		FF_INQUIRY_SEQ  ,
			
		FF_INVOICE_BILLLIST_SEQ  ,
			
		FF_JURISDICTION_CITY_SEQ  ,
			
		FF_LCLBRANCH_PRODUCT_SEQ  ,
			
		FF_LCLBRANCH_PRO_LS_SEQ  ,
			
		FF_LCLBRANCH_RATE_LIST_SEQ  ,
			
		FF_LCLBRANCH_RATE_SEQ  ,
			
		FF_LCLMAIN_PEERVIP_RULE_SEQ  ,
			
		FF_LCLMAIN_PERRVIP_LIST_SEQ  ,
			
		FF_LCLMAIN_PRODUCT_LEVEL_SEQ  ,
			
		FF_LCLMAIN_PRODUCT_LIST_SEQ  ,
			
		FF_LCLMAIN_PRODUCT_RULE_SEQ  ,
			
		FF_LCLMAIN_PRODUCT_SC_SEQ  ,
			
		FF_LCLMAIN_PRODUCT_SEQ  ,
			
		FF_LCLMAIN_PRODUCT_VIA_SEQ  ,
			
		FF_LCLMAIN_RATES_DETAIL_SEQ  ,
			
		FF_LCLMAIN_RATE_DETAIL_SEQ  ,
			
		FF_LCLMAIN_RATE_LIST_SEQ  ,
			
		FF_LCLMAIN_RATE_SEQ  ,
			
		FF_LCLPRODUCTSUPPLIERRULE_SEQ  ,
			
		FF_LCL_CUSTOMER_RULE_SEQ  ,
			
		FF_LCL_INQUIRY_PRODUCT_SEQ  ,
			
		FF_LCL_INQUIRY_SEQ  ,
			
		FF_LCL_ORDER_BOOKING_SEQ  ,
			
		FF_LCL_ORDER_CHARGE_SEQ  ,
			
		FF_LCL_ORDER_DESTFEE_SEQ  ,
			
		FF_LCL_PRODUCT_SEQ  ,
			
		FF_LCL_PRODUCT_SUPPLIER_SEQ  ,
			
		FF_LCL_RATES_DETAIL_SEQ  ,
			
		FF_LCL_RATE_CUSTOMER_SEQ  ,
			
		FF_LCL_RATE_SEQ  ,
			
		FF_LCL_SEARCHRATE_LOG_SEQ  ,
			
		FF_LCL_SURCHARGE_CUSTOMER_SEQ  ,
			
		FF_LCL_SURCHARGE_PORT_SEQ  ,
			
		FF_LCL_SURCHARGE_SEQ  ,
			
		FF_LEAGUE_SEQ  ,
			
		FF_LOAN_SEQ  ,
			
		FF_MAIL_INFO_SEQ  ,
			
		FF_MAIL_TEMPLATE_SEQ  ,
			
		FF_MONTHLY_BILL_SEQ  ,
			
		FF_NEWS_SEQ  ,
			
		FF_NOTICE_SEQ  ,
			
		FF_ORDER_PROFIT_SEQ  ,
			
		FF_ORDER_SUBSIDY_APPLY_SEQ  ,
			
		FF_ORDER_SUBSIDY_SEQ  ,
			
		FF_OVERWEIGHT_SURCHARGE_SEQ  ,
			
		FF_PAY_INFO_THUNES_SEQ  ,
			
		FF_PEERVIP_RULE_SEQ  ,
			
		FF_PRODUCT_LIST_SEQ  ,
			
		FF_PRODUCT_SEQ  ,
			
		FF_PRODUCT_SUPPLIER_LOG_SEQ  ,
			
		FF_PRODUCT_SUPPLIER_SEQ  ,
			
		FF_PRODUCT_SURCHARGE_SEQ  ,
			
		FF_PROT_CONTRAST_SEQ  ,
			
		FF_RAISE_QUOTA_SEQ  ,
			
		FF_RATE_CUSTOMER_SEQ  ,
			
		FF_RATE_DETAIL_OTHERFEE_SEQ  ,
			
		FF_RATE_DETAIL_SEQ  ,
			
		FF_RATE_LIST_SEQ  ,
			
		FF_RATE_PEERVIP_SEQ  ,
			
		FF_RATE_RULE_SEQ  ,
			
		FF_RATE_SEQ  ,
			
		FF_REEFER_SURCHARGE_SEQ  ,
			
		FF_REFEREE_COMPANY_SEQ  ,
			
		FF_RELATED_COMPANY_SEQ  ,
			
		FF_REPORT_DATAINFO_SEQ  ,
			
		FF_RTFCL_BOOKING_CONTAINER_SEQ  ,
			
		FF_RTFCL_CUSTOMER_RULE_SEQ  ,
			
		FF_RTFCL_INQUIRY_PRODUCT_SEQ  ,
			
		FF_RTFCL_INQUIRY_SEQ  ,
			
		FF_RTFCL_ORDER_BOOKING_SEQ  ,
			
		FF_RTFCL_ORDER_CONTAINER_SEQ  ,
			
		FF_RTFCL_ORDER_NO_SEQ  ,
			
		FF_RTFCL_ORDER_SEQ  ,
			
		FF_RTFCL_PRODUCT_LIST_SEQ  ,
			
		FF_RTFCL_PRODUCT_SEQ  ,
			
		FF_RTFCL_PRODUCT_SUPPLIER_SEQ  ,
			
		FF_RTFCL_PRODUCT_VIPRULE_SEQ  ,
			
		FF_RTFCL_RATE_CUSTOMER_SEQ  ,
			
		FF_RTFCL_RATE_DETAIL_SEQ  ,
			
		FF_RTFCL_RATE_LIST_SEQ  ,
			
		FF_RTFCL_RATE_SEQ  ,
			
		FF_RTFCL_SEARCHRATE_LOG_SEQ  ,
			
		FF_RTFCL_SURCHARGE_CUS_SEQ  ,
			
		FF_RTFCL_SURCHARGE_PRODUCT_SEQ  ,
			
		FF_RTFCL_SURCHARGE_SEQ  ,
			
		FF_RTLCL_CUSTOMER_RULE_SEQ  ,
			
		FF_RTLCL_INQUIRY_PRODUCT_SEQ  ,
			
		FF_RTLCL_INQUIRY_SEQ  ,
			
		FF_RTLCL_ORDER_BOOKING_SEQ  ,
			
		FF_RTLCL_ORDER_DESTFEE_SEQ  ,
			
		FF_RTLCL_ORDER_NO_SEQ  ,
			
		FF_RTLCL_ORDER_SEQ  ,
			
		FF_RTLCL_PRODUCT_LEVEL_SEQ  ,
			
		FF_RTLCL_PRODUCT_LIST_SEQ  ,
			
		FF_RTLCL_PRODUCT_SEQ  ,
			
		FF_RTLCL_PRODUCT_SUPPLIER_SEQ  ,
			
		FF_RTLCL_PRODUCT_VIPRULE_SEQ  ,
			
		FF_RTLCL_RATE_CUSTOMER_SEQ  ,
			
		FF_RTLCL_RATE_DETAIL_SEQ  ,
			
		FF_RTLCL_RATE_LIST_SEQ  ,
			
		FF_RTLCL_RATE_SEQ  ,
			
		FF_RTLCL_SEARCHRATE_LOG_SEQ  ,
			
		FF_RTLCL_SURCHARGE_CUS_SEQ  ,
			
		FF_RTLCL_SURCHARGE_PRODUCT_SEQ  ,
			
		FF_RTLCL_SURCHARGE_SEQ  ,
			
		FF_SCHEDULE_SEQ  ,
			
		FF_SCN_SEQ  ,
			
		FF_SCN_TEMPLATE_SEQ  ,
			
		FF_SENDMAIL_RATE_SEQ  ,
			
		FF_SERACHRATE_LOG_SEQ  ,
			
		FF_SPREAD_SEQ  ,
			
		FF_SPREAD_VIEW_SEQ  ,
			
		FF_SUBSIDY_SEQ  ,
			
		FF_SYSTEM_AUTHORITY_SEQ  ,
			
		FF_WRITEOFF_BILL_SEQ  ,
			
		FF_WRITE_OFF_SEQ  ,
			
		FILE_SEQ  ,
			
		FREEDETENTION_APPLY_SEQ  ,
			
		HELPINFO_SEQ  ,
			
		HELP_CLASS_SEQ  ,
			
		LCL_ORDER_BL_SEQ  ,
			
		LCL_ORDER_NO_SEQ  ,
			
		LCL_ORDER_SEQ  ,
			
		MAIL_TEMPLATE_SEQ  ,
			
		MESSAGE_SEQ  ,
			
		NEWS_SEQ  ,
			
		OI_ORDER_BL_SEQ  ,
			
		OI_ORDER_CONTAINER_SEQ  ,
			
		OI_ORDER_SEQ  ,
			
		ORDER_COMMENT_SEQ  ,
			
		ORDER_EIR_APPLY_SEQ  ,
			
		ORDER_EIR_SEQ  ,
			
		ORDER_NO_SEQ  ,
			
		ORDER_PROFIT_DETAIL_SEQ  ,
			
		ORGANIZATIONSEQ  ,
			
		OVERSEA_AGENCY_SEQ  ,
			
		PEER_PUSHRATE_JOB_SEQ  ,
			
		PEER_RATE_PUSH_SEQ  ,
			
		PEER_SENDMAIL_RATE_SEQ  ,
			
		PRODUCT_DEMAND_CARRIER_SEQ  ,
			
		PRODUCT_DEMAND_FF_SEQ  ,
			
		PRODUCT_DEMAND_SEQ  ,
			
		PUSH_RATE_JOB_SEQ  ,
			
		RECRUITMENT_SEQ  ,
			
		RTLCL_PRODUCT_SUP_RULE_SEQ  ,
			
		SAP_CUSTOMER_MAP_DETAIL_SEQ  ,
			
		SAP_CUSTOMER_MAP_SEQ  ,
			
		SAP_FEE_TYPE_MAP_SEQ  ,
			
		STAFFORGANIZESEQ  ,
			
		SURCHARGE_TEMPLATE_DETAIL_SEQ  ,
			
		SURCHARGE_TEMPLATE_SEQ  ,
			
		SYNC_RATE_CUSTOMER_SEQ  ,
			
		SYNC_TEU_JOB_SEQ  ,
			
		SYSCONFIGURE_SEQ  ,
			
		TICKET_SEQ  ,
			
		USERRIGHTSEQ  ,
			
		USER_SEQ  ,
			
		WEB_COMPANY_SEQ  ,
			
		WEB_CONTACT_SEQ  ,
			
		WEB_LOCATION_SEQ  ,
			
		WEB_ZONE_BRANCH_SEQ  ,
			
		WEB_ZONE_SEQ 	
	}
}