using System;
using System.Collections.Generic;

namespace UC2OracleDataContext.Models
{
    public partial class TASK_CONFIG
    {
        public decimal TASK_CONFIG_ID { get; set; }
        public decimal APPLICATION_ID { get; set; }
        public string APPLICATION_KEY { get; set; }
        public decimal TASK_ID { get; set; }
        public string TASK_CODE { get; set; }
        public string TASK_NAME { get; set; }
        public string TASK_REMARK { get; set; }
        public string TASK_OBJECT { get; set; }
        public decimal COMPANY_ID { get; set; }
        public string COMPANY_CODE { get; set; }
        public string EXECUTE_METHOD { get; set; }
        public decimal? INTERVALS { get; set; }
        public string DAYBYMONTH { get; set; }
        public byte? WEEKS { get; set; }
        public string TIMEBYDAY { get; set; }
        public DateTime? EFFECTIVE_FROM { get; set; }
        public DateTime? EFFECTIVE_TO { get; set; }
        public decimal? MULTI { get; set; }
        public decimal? STATUS { get; set; }
        public string P01 { get; set; }
        public string P02 { get; set; }
        public string P03 { get; set; }
        public string P04 { get; set; }
        public string P05 { get; set; }
        public string P06 { get; set; }
        public string P07 { get; set; }
        public string P08 { get; set; }
        public string P09 { get; set; }
        public string P10 { get; set; }
        public string P11 { get; set; }
        public string P12 { get; set; }
        public string P13 { get; set; }
        public string P14 { get; set; }
        public string P15 { get; set; }
        public string P16 { get; set; }
        public string P17 { get; set; }
        public string P18 { get; set; }
        public string P19 { get; set; }
        public string P20 { get; set; }
        public string P21 { get; set; }
        public string P22 { get; set; }
        public string P23 { get; set; }
        public string P24 { get; set; }
        public string P25 { get; set; }
        public string P26 { get; set; }
        public string P27 { get; set; }
        public string P28 { get; set; }
        public string P29 { get; set; }
        public string P30 { get; set; }
        public string P31 { get; set; }
        public string P32 { get; set; }
        public string P33 { get; set; }
        public string P34 { get; set; }
        public string P35 { get; set; }
        public string P36 { get; set; }
        public string P37 { get; set; }
        public string P38 { get; set; }
        public string P39 { get; set; }
        public string P40 { get; set; }
        public string P41 { get; set; }
        public string P42 { get; set; }
        public string P43 { get; set; }
        public string P44 { get; set; }
        public string P45 { get; set; }
        public string P46 { get; set; }
        public string P47 { get; set; }
        public string P48 { get; set; }
        public string P49 { get; set; }
        public string P50 { get; set; }
        public string P51 { get; set; }
        public string P52 { get; set; }
        public string P53 { get; set; }
        public string P54 { get; set; }
        public string P55 { get; set; }
        public string P56 { get; set; }
        public string P57 { get; set; }
        public string P58 { get; set; }
        public string P59 { get; set; }
        public string P60 { get; set; }
        public string P61 { get; set; }
        public string P62 { get; set; }
        public string P63 { get; set; }
        public string P64 { get; set; }
        public string P65 { get; set; }
        public string P66 { get; set; }
        public string P67 { get; set; }
        public string P68 { get; set; }
        public string P69 { get; set; }
        public string P70 { get; set; }
        public string P71 { get; set; }
        public string P72 { get; set; }
        public string P73 { get; set; }
        public string P74 { get; set; }
        public string P75 { get; set; }
        public string P76 { get; set; }
        public string P77 { get; set; }
        public string P78 { get; set; }
        public string P79 { get; set; }
        public string P80 { get; set; }
        public string P81 { get; set; }
        public string P82 { get; set; }
        public string P83 { get; set; }
        public string P84 { get; set; }
        public string P85 { get; set; }
        public string P86 { get; set; }
        public string P87 { get; set; }
        public string P88 { get; set; }
        public string P89 { get; set; }
        public string P90 { get; set; }
        public string P91 { get; set; }
        public string P92 { get; set; }
        public string P93 { get; set; }
        public string P94 { get; set; }
        public string P95 { get; set; }
        public string P96 { get; set; }
        public string P97 { get; set; }
        public string P98 { get; set; }
        public string P99 { get; set; }
        public bool? VALID { get; set; }
        public string REMARK { get; set; }
        public DateTime? LAST_RUN_TIME { get; set; }
        public DateTime? SUCCESS_RUN_TIME { get; set; }
        public decimal? MODIFY_USERID { get; set; }
        public string MODIFY_USERNAME { get; set; }
        public string MODIFY_FULLNAME { get; set; }
        public decimal? MODIFY_COMPANYID { get; set; }
        public DateTime MODIFY_DATETIME { get; set; }
        public decimal? CREATE_USERID { get; set; }
        public string CREATE_USERNAME { get; set; }
        public string CREATE_FULLNAME { get; set; }
        public decimal? CREATE_COMPANYID { get; set; }
        public DateTime CREATE_DATETIME { get; set; }
    }
}
